// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svvurkytdhwolobuehgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2dnVya3l0ZGh3b2xvYnVlaGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2Mjk3NjksImV4cCI6MjA2MjIwNTc2OX0.BTBqixZnwexpaa3T2_Lm0o1XqGpyeGy3PHXyqV8eamo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);